### ISSUE TITLE
Also import untagged frames

### ISSUE THREAD

**Issue by crispinha** [nklbdev/godot-aseprite-animation-importer#3]
I've got some aseprite files which contain a single untagged frame and I'd like to use them with this plugin - currently the imported spriteframes has no animations. Maybe it could put all the untagged frames into an "untagged" animation?

(I might have a go at implementing this myself tomorrow but I'm new to godot so no promises)

**Comment by nklbdev** [comment]
Relatively to each other, tags are located on the timeline in an arbitrary order and can overlap each other. But there is no frame break inside each tag.

If I take all the frames not included in any tag, there will be gaps between them. Technically I can create animation from them, but it will rarely make sense in reality.

But if there are no tags in the file at all, I can convert the entire timeline into one animation, and name it the same as Godot - "default"

It is good idea, thanks! I can add import setting to importer so that the user can control this.

**Comment by nklbdev** [comment]
I have implemented it! The importer supports .ace-files without tags and creates "default" animation. Now there are import parameters "Default Loop" and "Default Direction".

I also forced Aseprite to export trimmed, tightly packed frames.

I also replaced the "Inner Padding" option with "Extrude", which is not in the Aseprite CLI. It expands each frame by 1 pixel beyond its bounds with color of that pixels. This will help to avoid artifacts at the edges on rendering.

I haven't published a new release yet. If you need, download the latest version directly from the `main` branch
